# Conference Postmortem Template
content: Conference/Summer School Postmortem
description: Reflect and follow up after the event
due_date_days_difference: 5
children:
  -
    content: Summarize learnings
    description: Write a summary of what you learned/achieved
    due_date_days_difference: 1
  -
    content: Organize notes & materials
    description: Sort your notes, slides, papers, business cards
    due_date_days_difference: 2
  -
    content: Reach out to new contacts
    description: Thank new connections, send relevant info or ask follow-up questions
    due_date_days_difference: 3
  -
    content: Add action items to todo list
    description: Add any research, reading, or collaboration tasks to your todo list
    due_date_days_difference: 4
  -
    content: Update academic CV/website
    description: Add talks, posters, or experiences to your CV or website
    due_date_days_difference: 5
