# Networking Initial Reachout Template
content: Networking Initial Reachout
description: Reach out to researchers or peers during the event
children:
  -
    content: Draft intro message/email
    description: Prepare a personal introduction and connection message
  -
    content: Refine intro with AI
    description: Refine with AI or mentor for clarity and conciseness
  -
    content: Send reachout
    description: Send intro message via email, LinkedIn, Slack, or in-person
  -
    content: Make a note of response
    description: Record replies & next steps for each contact
    due_date_days_difference: 1
  -
    content: Schedule meeting/coffee
    description: Arrange a chat (if possible)
    due_date_days_difference: 2
