# Read Paper Template
content: Read Paper
description: Read a research paper
children:
  -
    content: Find paper
    description: Find the paper to read
    due_date_days_difference: -7
  -
    content: Print paper
    description: Print the paper
    due_date_days_difference: -6
  -
    content: Read paper
    description: Spend time reading the paper
  -
    content: Summarize paper
    description: Write a summary of the paper
    due_date_days_difference: 1
  -
    content: Discuss paper
    description: Discuss the content of the paper with peers
    due_date_days_difference: 2
