# Talk/Session Attendance Template
content: Talk/Session Attendance
description: Attend and get the most out of a talk/session
children:
  -
    content: Read abstract & speaker bio
    description: Skim abstract and bio before the talk
    due_date_days_difference: -1
  -
    content: Prepare 1-2 questions
    description: Think of questions to ask during/after the session
  -
    content: Attend talk & take notes
    description: Focus on main ideas, jot down questions
  -
    content: Summarize key points
    description: Write a summary of the talk
    due_date_days_difference: 1
  -
    content: Reach out to speaker (if relevant)
    description: Send a question or comment as a follow-up if interested
    due_date_days_difference: 2
