# Call Template
content: Call
description: Call someone
children:
  -
    content: Setup meeting
    description: Should be put on calendar.
    due_date_days_difference: -3
  -
    content: Prepare notes
    description: Prepare notes for the meeting
    due_date_days_difference: -1
  -
    content: Attend meeting
    description: Attend the meeting
  -
    content: Write minutes
    description: Write minutes for the meeting
  -
    content: E-Mail follow up
    description: Follow up on the meeting with notes
