# Feature Development Template
content: Feature Development
description: Implement a feature
children:
  -
    content: Define requirements
    description: Define the requirements for the feature
    due_date_days_difference: -10
  -
    content: Design feature
    description: Design the feature
    due_date_days_difference: -5
  -
    content: Develop feature
    description: Develop the feature
  -
    content: Test feature
    description: Test the feature
    due_date_days_difference: 2
