# Pull Request Review Template
content: Review PR
description: Review a pull request
children:
  -
    content: Read PR & Task content
    description: Read the pull request
  -
    content: Check code
    description: Check the code
  -
    content: Manually test the code
    description: Manually test the code along with unit tests and other checks
  -
    content: Write review
    description: Write the review
